experiment:
  name: "VMB_training"
  log_dir: "logs"
  output_dir: "output"
  checkpoint_dir: "checkpoints"
  model_type: "VMB"
  dataset_type: "VMB"
  seed: 11
  debug: false
  tags:
    - "VMB"
    - "MSE"

data_settings:
  nx: 512
  ny: 256
  batch_size: 10
  eigen_count: 0
  sample_directories:
    - "../datasets/datasets/dataset_VMB"
    # - "/net/slimdata/tunadata/seismic_imaging/experiments/multi_back/data/datasets/dataset_VMB_easy_small"


model_settings:
  in_channels: 2
  out_channels: 1
  decoder_layer_size: 256
  num_fno_layers: 4
  num_fno_modes: [190, 120]
  padding: 0
  dimension: 2
  latent_channels: 64
  loss_type: "L2"  # "L2" / "JAC"
  train_eigen_count: 0
  reg_param: 0.5 # not used for L2
  scale_factor: 1.0 # not used for L2
  learning_rate: 6e-4 #8e-4
  weight_decay: 1e-5

training_settings:
  accum_steps: 1
  num_epoch: 200 #500
  num_train: 6000
  num_test: 700
  num_samples: 6000
  shuffle_train: true
  shuffle_test: false
  enable_checkpointing: true
  log_checkpoint: false # log to neptune (cloud)
  checkpoint_interval: 1
  save_top_k: -1
  num_GPU: 1
  strategy: "ddp"

visualization_settings:
  save_to_disk: false
  log_to_neptune: true
  num_plots: 3
  check_val_every_n_epoch: 1
  plot_interval: 1

neptune:
  enabled: true
  project: "slim-gatech/DeFINO"
