base_config: ../ns_default.yaml

experiment:
  name: "n=1000_e=200_m=FNO_s=RFS_l=JAC"
  tags:
    - "200 Eigenvector"
    - "1000 samples"
    - "FNO"
    - "RFS"
    - "JAC"

data_settings:
  eigen_count: 400
  batch_size: 100

model_settings:
  train_eigen_count: 400

training_settings:
  accum_steps: 1
  num_epoch: 600
  num_train: 1000
  num_test: 150
  num_samples: 1000
  num_GPU: 4
  strategy: "ddp"